[package]
name = "context"
version = "0.70.0"
edition = "2024"
description = "A lightweight configurable POSIX shell"

[features]
default = []
python = ["cps/python"]

[[bin]]
name = "ctx"
path = "src/main.rs"

[dependencies]
crossterm = "0.28"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"
glob = "0.3"
libc = "0.2"
regex = "1"
wallust = "3.5"
serde_json = "1"

cps = { git = "https://github.com/Mapuse/CPS", rev = "c4ba21e185398558052acec3f0b4619b4e8c0678", default-features = false }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
